annaamazon/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^data/', include('data.urls'), name="data"),
    url(r'^', include('mainsite.urls'), name="mainsite"),
    url('^accounts/', include('django.contrib.auth.urls')),
]

data/urls.py
from django.conf.urls import url

from . import views

app_name = 'data'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^grouped_orders/', views.grouped_orders, name='grouped_orders'),
    url(r'^orders/', views.orders, name='orders'),
    url(r'^all_data/', views.all_data, name='all_data'),
    url(r'^cd_items/', views.cd_items, name='cd_items'),
    url(r'^inactive/', views.inactive, name='inactive'),
]

mainsite/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainsite'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^generic', views.generic, name='generic'),
    url(r'^elements', views.elements, name='elements'),
]

data/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mainsite/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

data/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from os import environ
from sqlalchemy import create_engine
from pandas import read_sql
import math
from django.contrib.auth.decorators import login_required

engine = create_engine(environ['DATABASE_URL'], echo=False).raw_connection()
# Create your views here.

@login_required
def index(request):
    col_query = read_sql("select * from all_items limit 0;", engine)
    return render(request, 'data/index.html', context={"columns":list(col_query)})

@login_required
def cd_items(request):
    col_query = read_sql("select * from all_items limit 0;", engine)
    return render(request, 'data/cd_items.html', context={"columns":list(col_query)})

@login_required
def orders(request):
    col_query = read_sql("select * from order_items limit 0;", engine)
    return render(request, 'data/orders.html', context={"columns":list(col_query)})

@login_required
def grouped_orders(request):
    return render(request, 'data/grouped_orders.html', context={"columns":['asin','title','dollar_volume','num_items','avg_price']})

@login_required
def inactive(request):
    col_query = read_sql("select * from inactive_items limit 0;", engine)
    return render(request, 'data/inactive.html', context={"columns":list(col_query)})

@login_required
def all_data(request):
    if request.is_ajax():
        where_clause = ""
        args = {
            'all':['all_items','index'],
            'oi': ['order_items','itemid'],
            'go': ["""(select 
                        asin, 
                        title,
                        sum( CAST(qnty_shipped as FLOAT) * CAST(item_price as FLOAT) ) as dollar_volume, 
                        count(*) as num_items, 
                        avg(CAST(item_price as FLOAT)) as avg_price
                    from 
                        order_items 
                    group by 
                        title, asin) grouped_orders""", 'asin'],
            'cd_items': ["""(select * from all_items where asin1 ~ '^\d+$') cd_items""", 'index'],
            'inactive':['inactive_items','index']
        }
        table_name = args[request.GET.get('arg1')][0]
        pk = args[request.GET.get('arg1')][1]
        for key, value in request.GET.items():
            #print(key, value)
            if key not in ['sidx','rows','_search','nd','sord','csrfmiddlewaretoken','page','arg1']:
                where_clause += """lower(CAST("%s" AS TEXT)) LIKE '%%%s%%' and """ % (key,value)
        where_clause = where_clause.rstrip(" and ")
        
        rows = int(request.GET.get('rows'))
        page = int(request.GET.get('page'))
        sidx = request.GET.get('sidx')
        sord = request.GET.get('sord')
        search = request.GET.get('_search')
        
        if search == "true":
            #print where_clause
            count_df = read_sql("""SELECT count(*) as the_count from %s where %s;""" % (table_name, where_clause),engine)
            df = read_sql("""SELECT * from %s where %s order by "%s" %s limit %s offset %s;""" % (table_name, where_clause, sidx, sord, rows, rows*page-rows) ,engine)
        else:
            count_df = read_sql("""SELECT count(*) as the_count from %s;""" % table_name, engine)
            df = read_sql("""SELECT * from %s order by "%s" %s limit %s offset %s;""" % (table_name, sidx, sord, rows, rows*page-rows),engine)    

        columns = list(df)

        d = df.to_dict()

        rows = []
        
        for index in d[pk]:
            new_row = {'id':d[pk][index]}
            cell = []
            for column in columns:
                cell.append(d[column][index])
                    
            new_row['cell'] = cell
            rows.append(new_row)
            
        if len(df.index) > 0:
            total = math.ceil(float(count_df.iloc[0]['the_count'])/len(df.index))
        else:
            total = 0
            
        data = {
                "total":total,
                "page":page,
                "records":count_df.iloc[0]['the_count'],
                "rows":rows
                }
        
        return HttpResponse(json.dumps(data), content_type='application/json')

mainsite/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'mainsite/index.html')

def generic(req):
    return render(req, 'mainsite/generic.html')

def elements(req):
    return render(req, 'mainsite/elements.html')

data/templates/data/base.html
{% load staticfiles %}
<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8">

	<title>Mondonect Data Portal</title>
	<meta name="description" content="Mondonect Data">
	<meta name="author" content="Tim Guild">

	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<!--[if lt IE 9]>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
	<![endif]-->
	
	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	
	<!--BOOTSTRAP-->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<!-- Free jqGrid -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.13.4/css/ui.jqgrid.min.css">
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.13.4/js/i18n/grid.locale-en.min.js"></script>-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.13.4/js/jquery.jqgrid.min.js"></script>
	
	<!-- Font Awesome -->
	<link rel="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
	
	
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="navbar-brand">Mondonect</div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'data:index' %}">All Items</a></li>
		<li><a href="{% url 'data:inactive' %}">Inactive</a></li>
		<li><a href="{% url 'data:cd_items' %}">CD Items</a></li>
        <li><a href="{% url 'data:orders' %}">Orders</a></li>
		<li><a href="{% url 'data:grouped_orders' %}">Grouped Orders</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout'  %}">Logout</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block content %}
{% endblock %}
</body>
</html>

data/templates/data/cd_items.html
{% extends 'data/base.html' %}

{% block content %}
<table id="grid"></table>

<script type="text/javascript">
	jQuery(function($){
	
		$('#grid').jqGrid({
			caption: "CD Items",
			url: "{% url 'data:all_data' %}",
			postData: { "csrfmiddlewaretoken" : "{{ csrf_token }}", "arg1" : "cd_items" },
			colModel: [
				{% for column in columns %}
					{ name : "{{column}}" },
				{% endfor %}
			],
			dataType: 'json',
			pager: true,
			guiStyle: "bootstrap",
			sortname: "index",
			sortorder: "asc",
			autowidth: true,
			viewrecords: true
		}).jqGrid('filterToolbar');
	
	});


</script>
{% endblock %}

data/templates/data/grouped_orders.html
{% extends 'data/base.html' %}

{% block content %}
<table id="grid"></table>

<script type="text/javascript">
	jQuery(function($){
	
		$('#grid').jqGrid({
			caption: "Grouped Orders 1 Year",
			url: "{% url 'data:all_data' %}",
			postData: { "csrfmiddlewaretoken" : "{{ csrf_token }}", "arg1" : "go" },
			colModel: [
				{% for column in columns %}
					{ name : "{{column}}" },
				{% endfor %}
			],
			dataType: 'json',
			pager: true,
			guiStyle: "bootstrap",
			sortname: "dollar_volume",
			sortorder: "desc",
			autowidth: true,
			viewrecords: true,
			rowList: [20,50,100]
		}).jqGrid('filterToolbar');
	
	});


</script>
{% endblock %}

data/templates/data/inactive.html
{% extends 'data/base.html' %}

{% block content %}
<table id="grid"></table>

<script type="text/javascript">
	jQuery(function($){
	
		$('#grid').jqGrid({
			caption: "All US Items",
			url: "{% url 'data:all_data' %}",
			postData: { "csrfmiddlewaretoken" : "{{ csrf_token }}", "arg1" : "inactive" },
			colModel: [
				{% for column in columns %}
					{ name : "{{column}}" },
				{% endfor %}
			],
			dataType: 'json',
			pager: true,
			guiStyle: "bootstrap",
			sortname: "index",
			sortorder: "asc",
			autowidth: true,
			viewrecords: true
		}).jqGrid('filterToolbar');
	
	});


</script>
{% endblock %}

data/templates/data/index.html
{% extends 'data/base.html' %}

{% block content %}
<table id="grid"></table>

<script type="text/javascript">
	jQuery(function($){
	
		$('#grid').jqGrid({
			caption: "All US Items",
			url: "{% url 'data:all_data' %}",
			postData: { "csrfmiddlewaretoken" : "{{ csrf_token }}" },
			colModel: [
				{% for column in columns %}
					{ name : "{{column}}" },
				{% endfor %}
			],
			dataType: 'json',
			pager: true,
			guiStyle: "bootstrap",
			sortname: "index",
			sortorder: "asc",
			autowidth: true,
			viewrecords: true
		}).jqGrid('filterToolbar');
	
	});


</script>
{% endblock %}

data/templates/data/orders.html
{% extends 'data/base.html' %}

{% block content %}
<table id="grid"></table>

<script type="text/javascript">
	jQuery(function($){
	
		$('#grid').jqGrid({
			caption: "Ordered Items",
			url: "{% url 'data:all_data' %}",
			postData: { "csrfmiddlewaretoken" : "{{ csrf_token }}", "arg1" : "oi" },
			colModel: [
				{% for column in columns %}
					{ name : "{{column}}" },
				{% endfor %}
			],
			dataType: 'json',
			pager: true,
			guiStyle: "bootstrap",
			sortname: "purchase_date",
			sortorder: "desc",
			autowidth: true,
			viewrecords: true
		}).jqGrid('filterToolbar');
	
	});


</script>
{% endblock %}

mainsite/templates/mainsite/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
	Retrospect by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Mondonect</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{% static 'js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'css/ie8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'css/ie9.css' %}" /><![endif]-->
	</head>
	<body class="landing">

		<!-- Header -->
			<header id="header" class="alt">
				<h1><a href="index.html">Mondonect</a></h1>
				<a href="#nav">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="{% url 'mainsite:index' %}">Home</a></li>
					<li><a href="{% url 'mainsite:generic' %}">Generic</a></li>
					<li><a href="{% url 'mainsite:elements' %}">Elements</a></li>
				</ul>
			</nav>
		{% block content %}
		
		{% endblock %}

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<ul class="icons">
						<li><a href="#" class="icon fa-facebook">
							<span class="label">Facebook</span>
						</a></li>
						<li><a href="#" class="icon fa-twitter">
							<span class="label">Twitter</span>
						</a></li>
						<li><a href="#" class="icon fa-instagram">
							<span class="label">Instagram</span>
						</a></li>
						<li><a href="#" class="icon fa-linkedin">
							<span class="label">LinkedIn</span>
						</a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Mondonect.</li>
						<li>Images: <a href="http://unsplash.com">Unsplash</a>.</li>
						<li>Design: <a href="http://templated.co">TEMPLATED</a>.</li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/skel.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="{% static 'js/ie/respond.min.js' %}"></script><![endif]-->
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

mainsite/templates/mainsite/generic.html
{% extends 'mainsite/base.html' %}

{% load staticfiles %}

{% block content %}

		<!-- Main -->
			<section id="main" class="wrapper">
				<div class="container">

					<header class="major special">
						<h2>Generic</h2>
						<p>Lorem ipsum dolor sit amet nullam id egestas urna aliquam</p>
					</header>

					<a href="#" class="image fit"><img src="{% static 'images/pic11.jpg' %}" alt="" /></a>
					<p>Vis accumsan feugiat adipiscing nisl amet adipiscing accumsan blandit accumsan sapien blandit ac amet faucibus aliquet placerat commodo. Interdum ante aliquet commodo accumsan vis phasellus adipiscing. Ornare a in lacinia. Vestibulum accumsan ac metus massa tempor. Accumsan in lacinia ornare massa amet. Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan.</p>
					<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet Ac interdum ac non praesent. Cubilia lacinia interdum massa faucibus blandit nullam. Accumsan phasellus nunc integer. Accumsan euismod nunc adipiscing lacinia erat ut sit. Arcu amet. Id massa aliquet arcu accumsan lorem amet accumsan commodo odio cubilia ac eu interdum placerat placerat arcu commodo lobortis adipiscing semper ornare pellentesque.</p>
					<p>Amet nibh adipiscing adipiscing. Commodo ante vis placerat interdum massa massa primis. Tempus condimentum tempus non ac varius cubilia adipiscing placerat lorem turpis at. Aliquet lorem porttitor interdum. Amet lacus. Aliquam lobortis faucibus blandit ac phasellus. In amet magna non interdum volutpat porttitor metus a ante ac neque. Nisi turpis. Commodo col. Interdum adipiscing mollis ut aliquam id ante adipiscing commodo integer arcu amet blandit adipiscing arcu ante.</p>

				</div>
			</section>

{% endblock %}

mainsite/templates/mainsite/index.html
{% extends 'mainsite/base.html' %}

{% load staticfiles %}

{% block content %}

		<!-- Banner -->
			<section id="banner">
				<i class="icon fa-diamond"></i>
				<h2>Fashion in Export</h2>
				<p>Putting our Customers First</p>
				<ul class="actions">
					<li><a href="#" class="button big special">Learn More</a></li>
				</ul>
			</section>

		<!-- One -->
			<section id="one" class="wrapper style1">
				<div class="inner">
					<article class="feature left">
						<span class="image"><img src="{% static 'images/pic01.jpg' %}" alt="" /></span>
						<div class="content">
							<h2>Integer vitae libero acrisus egestas placerat  sollicitudin</h2>
							<p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est.</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">More</a>
								</li>
							</ul>
						</div>
					</article>
					<article class="feature right">
						<span class="image"><img src="{% static 'images/pic02.jpg' %}" alt="" /></span>
						<div class="content">
							<h2>Integer vitae libero acrisus egestas placerat  sollicitudin</h2>
							<p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est.</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">More</a>
								</li>
							</ul>
						</div>
					</article>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper special">
				<div class="inner">
					<header class="major narrow">
						<h2>Aliquam Blandit Mauris</h2>
						<p>Ipsum dolor tempus commodo turpis adipiscing Tempor placerat sed amet accumsan</p>
					</header>
					<div class="image-grid">
						<a href="#" class="image"><img src="{% static 'images/pic03.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic04.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic05.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic06.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic07.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic08.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic09.jpg' %}" alt="" /></a>
						<a href="#" class="image"><img src="{% static 'images/pic10.jpg' %}" alt="" /></a>
					</div>
					<ul class="actions">
						<li><a href="#" class="button big alt">Tempus Aliquam</a></li>
					</ul>
				</div>
			</section>

		<!-- Three -->
			<section id="three" class="wrapper style3 special">
				<div class="inner">
					<header class="major narrow	">
						<h2>Magna sed consequat tempus</h2>
						<p>Ipsum dolor tempus commodo turpis adipiscing Tempor placerat sed amet accumsan</p>
					</header>
					<ul class="actions">
						<li><a href="#" class="button big alt">Magna feugiat</a></li>
					</ul>
				</div>
			</section>

		<!-- Four -->
			<section id="four" class="wrapper style2 special">
				<div class="inner">
					<header class="major narrow">
						<h2>Get in touch</h2>
						<p>Ipsum dolor tempus commodo adipiscing</p>
					</header>
					<form action="#" method="POST">
						<div class="container 75%">
							<div class="row uniform 50%">
								<div class="6u 12u$(xsmall)">
									<input name="name" placeholder="Name" type="text" />
								</div>
								<div class="6u$ 12u$(xsmall)">
									<input name="email" placeholder="Email" type="email" />
								</div>
								<div class="12u$">
									<textarea name="message" placeholder="Message" rows="4"></textarea>
								</div>
							</div>
						</div>
						<ul class="actions">
							<li><input type="submit" class="special" value="Submit" /></li>
							<li><input type="reset" class="alt" value="Reset" /></li>
						</ul>
					</form>
				</div>
			</section>

{% endblock %}